from turtle import Turtle
t = Turtle()
t.up()
t.speed(0)
t.screen.bgcolor("royalblue4")
def Clear():
    t.setheading(180)
    t.color("royalblue4")
    t.down()
    t.begin_fill()
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    
def DA():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(30)
    
    t.color("red")
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.left(120)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.end_fill()
    t.up()
    t.right(30)        
    t.forward(30)
    t.left(90)
    t.forward(26)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("A", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("A", move=False,align="center",font=FONT)
    t.right(90)
    
def D3():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(30)
    t.color("red")
    t.down()
    
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.down()
    
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.down()
    
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(90)
    t.left(90)
    t.forward(26)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("3", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("3", move=False,align="center",font=FONT)
    t.right(90)

def D2():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(30)
    t.color("red")
    t.down()
    
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(85)
    t.left(90)
    t.forward(26)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("2", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("2", move=False,align="center",font=FONT)
    t.right(90)

def D4():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(20)
    t.color("red")
    t.down()
    
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.right(30)
    t.right(180)
    t.forward(70)
    t.left(90)
    t.forward(20)
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(85)
    t.left(90)
    t.forward(15)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("4", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("4", move=False,align="center",font=FONT)
    t.right(90)

def D5():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()

    t.color("red")
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(40)
    t.begin_fill()
    t.right(30)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.right(120)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(30)
    
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(20)
    t.down()
    
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.right(30)
    t.right(180)
    t.forward(70)
    t.left(90)
    t.forward(20)
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(85)
    t.left(90)
    t.forward(15)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("5", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("5", move=False,align="center",font=FONT)
    t.right(90)

def D6():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.color("red")
    t.down()
    
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.right(30)
    t.right(180)
    t.forward(80)
    t.left(90)
    t.forward(20)
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(90)
    t.left(90)
    t.forward(15)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("6", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("6", move=False,align="center",font=FONT)
    t.right(90)
    
def D7():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()

    t.color("red")
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(60)
    t.begin_fill()
    t.right(30)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.right(120)
    t.left(90)
    t.forward(60)
    t.right(90)
    t.forward(30)
    

    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.right(30)
    t.right(180)
    t.forward(80)
    t.left(90)
    t.forward(20)
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(90)
    t.left(90)
    t.forward(15)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("7", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("7", move=False,align="center",font=FONT)
    t.right(90)

def D8():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()

    t.color("red")
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.begin_fill()
    t.right(30)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.right(120)
    t.right(90)
    t.forward(30)
    t.begin_fill()
    t.right(30)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.right(120)
    t.left(90)
    t.forward(60)
    t.right(90)
    t.forward(30)
    

    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.right(30)
    t.right(180)
    t.forward(80)
    t.left(90)
    t.forward(20)
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(90)
    t.left(90)
    t.forward(15)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("8", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("8", move=False,align="center",font=FONT)
    t.right(90)

def D10():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()

    t.color("red")
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(25)
    t.begin_fill()
    t.right(30)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.right(120)
    t.right(90)
    t.forward(40)
    t.begin_fill()
    t.right(30)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.right(120)
    t.left(90)
    t.forward(65)
    t.right(90)
    t.forward(30)
    

    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.right(30)
    t.right(180)
    t.forward(80)
    t.left(90)
    t.forward(20)
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(90)
    t.left(90)
    t.forward(13)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("10", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(45)
    t.right(90)
    t.forward(85)
    t.write("10", move=False,align="center",font=FONT)
    t.right(90)

def D9():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()

    t.color("red")
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(40)
    t.begin_fill()
    t.right(30)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.right(120)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.forward(30)
    

    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()

    t.right(30)
    t.right(180)
    t.forward(80)
    t.left(90)
    t.forward(20)
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    t.left(120)
    t.right(60)
    t.left(90)
    t.left(180)
    t.forward(20)
    t.left(90)
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.left(60)
    t.forward(10)
    t.end_fill()
    t.up()
    
    t.right(30)
    t.right(180)
    t.forward(90)
    t.left(90)
    t.forward(15)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("9", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("9", move=False,align="center",font=FONT)
    t.right(90)

def DJ():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(30)
    
    t.color("red")
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.left(120)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.end_fill()
    t.up()
    t.right(30)        
    t.forward(30)
    t.left(90)
    t.forward(26)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("J", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("J", move=False,align="center",font=FONT)
    t.right(90)

def DQ():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(30)
    
    t.color("red")
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.left(120)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.end_fill()
    t.up()
    t.right(30)        
    t.forward(30)
    t.left(90)
    t.forward(26)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("Q", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("Q", move=False,align="center",font=FONT)
    t.right(90)

def DK():
    t.setheading(180)
    t.color("white")
    t.down()
    t.begin_fill()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(60)
    t.end_fill()
    t.up()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(30)
    
    t.color("red")
    t.down()
    t.begin_fill()
    t.left(60)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.left(120)
    t.forward(20)
    t.left(60)
    t.forward(20)
    t.end_fill()
    t.up()
    t.right(30)        
    t.forward(30)
    t.left(90)
    t.forward(26)
    fontsize = 10
    FONT = ("Arial",fontsize,"bold")
    t.write("K", move=False,align="center",font=FONT)
    t.right(180)
    t.forward(50)
    t.right(90)
    t.forward(85)
    t.write("K", move=False,align="center",font=FONT)
    t.right(90)





t.up()
t.goto(-250,200)
t.width(100)
t.color("white")
t.down()
t.goto(250,200)
t.up()
t.color("Red")
t.goto(0,160)
fontsize = 50
FONT = ("roman",fontsize,"bold")
t.write("Higher or Lower?", move=False,align="center",font=FONT)
    
t.up()
t.goto(0,125)
t.color("white")
fontsize = 12
FONT = ("arial",fontsize,"bold")
t.write("By: Alif Nafili", move=False,align="center",font=FONT)
t.goto(0,100)
t.color("paleturquoise")
t.write("The computer will display a random arrangement of cards from Ace to King.", move=False,align="center",font=FONT)
t.goto(0,75)
t.write("It will display the selection individually.", move=False,align="center",font=FONT)
t.goto(0,50)
t.write("You must decide whether the next card is higher or lower.", move=False,align="center",font=FONT)
a = 1
import random
while a > 0:
    b = 0
    c = []
    t.color("cornsilk")
    t.width(1)
    t.goto(0,-200)
    t.write("Turn on assisted mode?", move=False,align="center",font=FONT)
    t.goto(0,-225)
    t.write("Input 1 for Yes", move=False,align="center",font=FONT)
    t.goto(0,-250)
    t.write("Input 0 for No", move=False,align="center",font=FONT)
    r = int(input("Turn on assisted mode?"))
    s = 13
    t.down()
    t.color("royalblue4")
    t.begin_fill()
    t.goto(-200,-250)
    t.goto(-200,-150)
    t.goto(200,-150)
    t.goto(200,-250)
    t.goto(0,-250)
    t.end_fill()
    t.up()
    t.color("cornsilk")
    t.goto(0,-200)
    t.write("Turn on admin mode?", move=False,align="center",font=FONT)
    t.goto(0,-225)
    t.write("Input admin code for Yes", move=False,align="center",font=FONT)
    t.goto(0,-250)
    t.write("Input 0 for No", move=False,align="center",font=FONT)
    pi = float(input("Turn on admin mode?"))
    t.down()
    t.color("royalblue4")
    t.begin_fill()
    t.goto(-200,-250)
    t.goto(-200,-150)
    t.goto(200,-150)
    t.goto(200,-250)
    t.goto(0,-250)
    t.end_fill()
    t.up()
    t.goto(0,-200)
    while b < 13:
        d = random.randint(1,13)
        e = d in c
        if e == False:
            c.append(d)
            b += 1
        else:
            b +=0
    b = 0
    card = c[12]
    while b < 13:
        g = c[b]
        z = b
        t.goto(-30,-60)
        if g == 1:
            DA()
        if g == 2:
            D2()
        if g == 3:
            D3()
        if g == 4:
            D4()
        if g == 5:
            D5()
        if g == 6:
            D6()
        if g == 7:
            D7()
        if g == 8:
            D8()
        if g == 9:
            D9()
        if g == 10:
            D10()
        if g == 11:
            DJ()
        if g == 12:
            DQ()
        if g == 13:
            DK() 
        temp = 0
        if pi == 3.1415926535897932384626433832795028841971693:
            t.goto(0,-100)
            t.color("lightsalmon")
            t.write(c, move=False,align="center",font=FONT)
        if r == 1:
            pos = 0
            neg = 0
            timer = b
            l = 0
            s-=1
            while timer < 12:
                timer += 1
                l = c[timer]
                if l < g:
                    neg += 1
                else:
                    pos += 1
            t.goto(0,-125)
            t.color("lightsalmon")
            text = "chance of higher: " + str(pos/s)
            t.write(text, move=False,align="center",font=FONT)
            t.goto(0,-150)
            text = "chance of lower: " + str(neg/s)
            t.write(text, move=False,align="center",font=FONT)
        
        t.color("cornsilk")
        t.goto(0,-200)
        t.write("Will the next card be higher or lower?", move=False,align="center",font=FONT)
        t.goto(0,-225)
        t.write("Input 1 for higher", move=False,align="center",font=FONT)
        t.goto(0,-250)
        t.write("Input 0 for lower", move=False,align="center",font=FONT)
        f = int(input("Will the next card be higher or lower?"))
        
        t.goto(0,-175)
        t.down()
        t.color("royalblue4")
        t.begin_fill()
        t.goto(-200,-175)
        t.goto(-200,50)
        t.goto(200,50)
        t.goto(200,-175)
        t.goto(0,-175)
        t.end_fill()
        t.up()
        
        i = f
        b += 1
        h = c[b]
        if f == 1:
            if h > g:
                t.goto(0,-175)
                t.color("lime")
                t.write("Correct", move=False,align="center",font=FONT)
                if h == card:
                    t.goto(0,-275)
                    t.color("lime")
                    t.write("Congrats you win!!!!", move=False,align="center",font=FONT)
                    b = 236978
            else:
                t.goto(0,-275)
                t.color("tomato")
                t.write("Incorrect, the next card was:", move=False,align="center",font=FONT)
                t.goto(-30,-60)
                if h == 1:
                    DA()
                if h == 2:
                    D2()
                if h == 3:
                    D3()
                if h == 4:
                    D4()
                if h == 5:
                    D5()
                if h == 6:
                    D6()
                if h == 7:
                    D7()
                if h == 8:
                    D8()
                if h == 9:
                    D9()
                if h == 10:
                    D10()
                if h == 11:
                    DJ()
                if h == 12:
                    DQ()
                if h == 13:
                    DK()
                b = 493678

        else:
            if h < g:
                t.goto(0,-175)
                t.color("lime")
                t.write("Correct", move=False,align="center",font=FONT)
                if h == card:
                    t.goto(0,-275)
                    t.color("lime")
                    t.write("Congrats you win!!!!", move=False,align="center",font=FONT)
                    b = 236978
            else:
                t.goto(0,-275)
                t.color("tomato")
                t.write("Incorrect, the next card was:", move=False,align="center",font=FONT)
                t.goto(-30,-60)
                if h == 1:
                    DA()
                if h == 2:
                    D2()
                if h == 3:
                    D3()
                if h == 4:
                    D4()
                if h == 5:
                    D5()
                if h == 6:
                    D6()
                if h == 7:
                    D7()
                if h == 8:
                    D8()
                if h == 9:
                    D9()
                if h == 10:
                    D10()
                if h == 11:
                    DJ()
                if h == 12:
                    DQ()
                if h == 13:
                    DK()
                b = 23697
    if b == 236978:
        t.goto(0,-300)
        t.color("lime")
        t.write("Yay!", move=False,align="center",font=FONT)
        t.goto(-120,-60)
        DA()
        t.goto(-100,-60)
        D2()
        t.goto(-80,-60)
        D3()
        t.goto(-60,-60)
        D4()
        t.goto(-40,-60)
        D5()
        t.goto(-20,-60)
        D6()
        t.goto(0,-60)
        D7()
        t.goto(20,-60)
        D8()
        t.goto(40,-60)
        D9()
        t.goto(60,-60)
        D10()
        t.goto(80,-60)
        DJ()
        t.goto(100,-60)
        DQ()
        t.goto(120,-60)
        DK()
        
    else:
        t.goto(0,-300)
        t.color("tomato")
        text = "Your score was: " + str(z)
        t.write(text, move=False,align="center",font=FONT)
    a = int(input())

